title: dodslaser
baseURL: https://dodslaser.com/
author: Erik Demitz-Helin
languageCode: en-US
theme: hugo-laserbear
relativeURLs: true

enableRobotsTXT: true
disableKinds:
  - taxonomy
ignoreErrors:
  - error-disable-taxonomy
permalinks:
  blog: /:slug/
  tags: /blog/:slug

params:
  description: Various projects and ramblings, sometimes about bioinformatics
  favicon: images/favicon.png
  images:
    - images/share.png
  title: dodslaser
  # hideMadeWithLine: true
  # dateFormat: 2006-01-02

server:
  headers:
  - for: /**.html
    values:
      Content-Security-Policy: default-src 'none'; img-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block